package net.runelite.client.plugins.cupidbot.brimhavenagilitybot;

public enum BrimhavenBotState
{
	STARTING,
	BANKING,
	TELEPORTING_TO_LUMBRIDGE,
	WALKING_TO_PORT_SARIM,
	TAKING_BOAT_TO_MUSA_POINT,
	WALKING_TO_BRIMHAVEN,
	WAITING_FOR_ENTRY_COOLDOWN,
	PAYING_ENTRY,
	ENTERING_ARENA,
	WAITING_FOR_DISPENSER,
	MOVING_TO_DISPENSER,
	TAGGING_DISPENSER,
	EATING,
	STOPPED
}
